version = 1
SPDX-PackageName = "Gardener gardenlogin"
SPDX-PackageSupplier = "The Gardener project <gardener@googlegroups.com>"
SPDX-PackageDownloadLocation = "https://github.com/gardener/gardenlogin"

[[annotations]]
path = [
  ".ci/**",
  ".dockerignore",
  ".github/**",
  ".gitignore",
  ".gimps.yaml",
  ".golangci.yaml",
  ".ocm/branch-info.yaml",
  "CODEOWNERS",
  "OWNERS",
  "OWNERS_ALIASES",
  "go.mod",
  "go.sum",
  "LATEST",
  "VERSION"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2021-2024 SAP SE or an SAP affiliate company and Gardener contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["**.md"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2021-2024 SAP SE or an SAP affiliate company and Gardener contributors"
SPDX-License-Identifier = "CC-BY-4.0"
